build oselas:
    #!/usr/bin/env bash

    if [[ {{oselas}} == "2022.10" ]]; then
        TOOLCHAIN="oselas.toolchain-2022.10-arm-v7a-linux-gnueabihf"
        TOOLCHAIN="$TOOLCHAIN oselas.toolchain-2022.10.0-aarch64-v8a-linux-gnu"
    elif [[ {{oselas}} == "2021.07" ]]; then
        TOOLCHAIN="oselas.toolchain-2021.07.0-arm-v7a-linux-gnueabihf"
        TOOLCHAIN="$TOOLCHAIN oselas.toolchain-2021.07.0-arm-v7a-linux-gnueabihf"
    fi

    IMAGE="build-env-arm-multi:OSELAS.Toolchain-{{oselas}}"
    podman build -t $IMAGE --build-arg=TOOLCHAIN="$TOOLCHAIN" ~/work/build-envs/arm-multi
