build oselas:
    #!/usr/bin/env bash

    set -x

    if [[ {{oselas}} == "2022.10" ]]; then
        TOOLCHAIN="oselas.toolchain-2022.10-arm-v7a-linux-gnueabihf"
        TOOLCHAIN="$TOOLCHAIN oselas.toolchain-2022.10-aarch64-v8a-linux-gnu"
    elif [[ {{oselas}} == "2023.07" ]]; then
        TOOLCHAIN="oselas.toolchain-2023.07-arm-v7a-linux-gnueabihf"
        TOOLCHAIN="$TOOLCHAIN oselas.toolchain-2023.07-aarch64-v8a-linux-gnu"
    elif [[ {{oselas}} == "2021.07" ]]; then
        TOOLCHAIN="oselas.toolchain-2021.07.0-arm-v7a-linux-gnueabihf"
        TOOLCHAIN="$TOOLCHAIN oselas.toolchain-2021.07.0-arm-v7a-linux-gnueabihf"
    fi

    IMAGE="build-env-arm-multi:OSELAS.Toolchain-{{oselas}}"
    podman build -t $IMAGE --build-arg=TOOLCHAIN="$TOOLCHAIN" $PRJ_ROOT/build-envs/arm-multi
