PTXDIST_VERSION := `grep CONFIGFILE_VERSION configs/ptxconfig | cut -d = -f2 | sed 's/"//g'`
PTXDIST_PLATFORM := "configs" + "/platform-" + env_var('PLATFORM') + "/" + "platformconfig"
TOOLCHAIN_VERSION := `grep CROSSCHAIN_VENDOR configs/platform-$PLATFORM/platformconfig | cut -d = -f2 | sed 's/"//g'`
IMAGE := "ptxdist-" + PTXDIST_VERSION + "-build-env-arm-multi:" + TOOLCHAIN_VERSION

alias b := build

cmd := 'bash -i'

platform:
    #!/usr/bin/env bash
    files=$(shopt -s nullglob dotglob; echo configs/platform-*)
    if (( ${#files} )); then
      PLATFORM=$(dialog --clear \
                      --stdout \
                      --title "Select Platform" \
                      --fselect configs/ 20 70)
    fi
    echo $PLATFORM

build:
    podman build -q -t {{IMAGE}} --build-arg=PTXDIST_VERSION={{PTXDIST_VERSION}} --build-arg=TOOLCHAIN_VERSION={{TOOLCHAIN_VERSION}} $PRJ_ROOT/build-envs/ptxdist-build-env

ps:
    podman ps --all --storage

@connect *command=cmd: build
    cd {{invocation_directory()}} && \
    podman run --rm -it --userns=keep-id \
    --workdir /bsp \
    --volume "$(pwd)":/bsp \
    --volume /opt/ptxdist/src:/bsp/src \
    --network=host \
    {{IMAGE}} \
    {{command}}

ptxdist *parameters:
    cd {{invocation_directory()}} && \
    just connect ptxdist {{parameters}}

ptxdist-platform:
    cd {{invocation_directory()}} && \
    just ptxdist platform {{PTXDIST_PLATFORM}}

at1130 *parameters:
    cd {{invocation_directory()}} && \
    just ptxdist --platformconfig=configs/platform-at1130/platformconfig {{parameters}} 
